name: Publish scan alerts

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ./test.sarif
